## check development version of gamboostLSS
## see http://docs.travis-ci.com/user/languages/r/

# ## test multiple directories 
# ## (see https://lord.io/blog/2014/travis-multiple-subdirs/)
# env:
#  - TEST_DIR=patch/
#  - TEST_DIR=pkg/

language: r
sudo: required

## change directory before installation 
## as R packages are not available elsewise
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-science texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils texlive-latex-recommended texlive-latex-extra
#  - cd $TEST_DIR

r_github_packages:
  - boost-R/mboost
  - hofnerb/stabs
  - jimhester/covr
  
after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
